version: '3.8'

services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    # ports:
    #   - "27364:8000"
    volumes:
      - ./app:/app/app
    environment:
      - SECRET_KEY=your-secret-key-change-in-production
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION=requests
      - USE_CUDA=1  # Установите 1, если хотите использовать GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - qdrant
    restart: always
    command: >
      sh -c "
        uv run python wait-for-it.py &&
        uv run uvicorn main:app --host 0.0.0.0 --port 8000
      "


  qdrant:
    image: qdrant/qdrant:latest
    # ports:
    #   - "6333:6333"
    #   - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_CORS=true
    restart: always

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "27365:8501"
    volumes:
      - ./frontend/main.py:/app/main.py
      - ./scripts:/scripts
    working_dir: /app
    environment:
      API_URL: "http://api:8000"
    command: >
      sh -c "streamlit run main.py --server.port=8501"

volumes:
  qdrant_data:

